### ISSUE TITLE
Problems with prioritize.py script

### ISSUE THREAD

**Issue by asmaamirkhan** [kili-technology/automl#61]
Hello, 

I faced the following problems while running [prioritize.py](https://github.com/kili-technology/automl/blob/main/prioritize.py) script:
1. Firstly, I got the following error when I ran it in the way you specified in the readme file:

```bash
python prioritize.py     --api-key <MY_API_KEY>     --project-id <MY_PROJECT_ID> 
Traceback (most recent call last):
  File "prioritize.py", line 470, in <module>
    main()
  File "<ENV_PATH>/kili/lib/python3.7/site-packages/click/core.py", line 1130, in __call__
    return self.main(*args, **kwargs)
  File "<ENV_PATH>/kili/lib/python3.7/site-packages/click/core.py", line 1055, in main
    rv = self.invoke(ctx)
  File "<ENV_PATH>/kili/lib/python3.7/site-packages/click/core.py", line 1404, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "<ENV_PATH>/kili/lib/python3.7/site-packages/click/core.py", line 760, in invoke
    return __callback(*args, **kwargs)
TypeError: main() missing 2 required positional arguments: 'model_name' and 'model_repository'
```

Actually, I couldn't exactly understand the problem, but I noticed that it's a problem with the `click` module. It worked when I added the following couple of lines to the script:

```py
@click.option("--model-name", default=None, help="Model name (eg. bert-base-cased)")
@click.option("--model-repository", default=None, help="Model repository (eg. huggingface)")
```

I ran the old command without any change, and it worked. Did I break the working logic of the script? 

> I will describe the other problem in the comments

**Comment by asmaamirkhan** [comment]
The other problem was solved in 149b8c5 2 hours ago 😅🎉

**Comment by FlorianLeRoyKili** [comment]
Hello Asmaa, Thanks again for your inputs. 
We are working in updating the code to have the assets fetched outside the yaml in Object Detection Task, but in the meantime, we will correct the mistakes of the previous commit you pointed out. Thanks !

**Comment by FlorianLeRoyKili** [comment]
Fixed with https://github.com/kili-technology/automl/pull/54
Thanks again Asmaa !
